create table Account (
    account_id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (account_id)
);

create table Ad_Config (
    id bigint generated by default as identity,
    enable boolean,
    format bigint,
    mediation bigint,
    primary key (id)
);

create table Ad_Format (
    id bigint generated by default as identity,
    format varchar(255) not null,
    primary key (id)
);

create table Application (
    id bigint generated by default as identity,
    name varchar(255) not null,
    account bigint,
    primary key (id)
);

create table Country (
    id bigint generated by default as identity,
    code varchar(255) not null,
    country varchar(255) not null,
    primary key (id)
);

create table Country_Code (
    id bigint generated by default as identity,
    code varchar(255) not null,
    country bigint,
    primary key (id)
);

create table Mediation (
    id bigint generated by default as identity,
    network bigint,
    application bigint,
    primary key (id)
);

create table Network (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table Network_CountryCodes (
    network_id bigint not null,
    country_code_id bigint not null,
    primary key (network_id, country_code_id)
);

create table Network_Token_Auth (
    net_account_id bigint generated by default as identity,
    token varchar(255) not null,
    account_id bigint,
    network bigint not null,
    primary key (net_account_id)
);

alter table Ad_Config
    add constraint FKdl5lv9xbqpeq59r7jcrrto20l
    foreign key (format)
    references Ad_Format;

alter table Ad_Config
    add constraint FK4eo3ywfbhnepw2fhi4grwa0qi
    foreign key (mediation)
    references Mediation;

alter table Application
    add constraint FKk9cohtqs9g0mwxw16phum8klf
    foreign key (account)
    references Account;

alter table Country_Code
    add constraint FKhje08pr8ihgm1rmr60v5imn0q
    foreign key (country)
    references Country;

alter table Mediation
    add constraint FK5vni3lu0c0le39ru5apmcgg9l
    foreign key (network)
    references Network;

alter table Mediation
    add constraint FKq1f0fju9e2qfpxrlp66aes7e1
    foreign key (application)
    references Application;

alter table Network_CountryCodes
    add constraint FK2i4nd9dby47937ttvnmukcvbn
    foreign key (country_code_id)
    references Country_Code;

alter table Network_CountryCodes
    add constraint FK9o0e23kcmceilp41054s8l1et
    foreign key (network_id)
    references Network;

alter table Network_Token_Auth
    add constraint FKke4937p9sj4caf6or6hwy9lu1
    foreign key (account_id)
    references Account;

alter table Network_Token_Auth
    add constraint FKk0creb3wkyu5cs0nshhub0vai
    foreign key (network)
    references Network;